import pandas as pd

df_movies = pd.read_csv('Datasets/imdb_1000.csv')

print(df_movies.head())

#  star_rating                     title content_rating   genre  duration                                        actors_list
# 0          9.3  The Shawshank Redemption              R   Crime       142  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...
# 1          9.2             The Godfather              R   Crime       175    [u'Marlon Brando', u'Al Pacino', u'James Caan']
# 2          9.1    The Godfather: Part II              R   Crime       200  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...
# 3          9.0           The Dark Knight          PG-13  Action       152  [u'Christian Bale', u'Heath Ledger', u'Aaron E...
# 4          8.9              Pulp Fiction              R   Crime       154  [u'John Travolta', u'Uma Thurman', u'Samuel L....

# Filter Movies with Genre : Action, Drama, Western

print(df_movies[(df_movies.genre == 'Action') | (df_movies.genre == 'Drama') | (df_movies.genre == 'Western')].head())
# star_rating                           title content_rating    genre  duration                                        actors_list
# 3           9.0                 The Dark Knight          PG-13   Action       152  [u'Christian Bale', u'Heath Ledger', u'Aaron E...
# 5           8.9                    12 Angry Men      NOT RATED    Drama        96  [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...
# 6           8.9  The Good, the Bad and the Ugly      NOT RATED  Western       161  [u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...
# 9           8.9                      Fight Club              R    Drama       139  [u'Brad Pitt', u'Edward Norton', u'Helena Bonh...
# 11          8.8                       Inception          PG-13   Action       148  [u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'...

print(df_movies[df_movies.genre.isin(['Action','Drama','Western'])].head())

# star_rating                           title content_rating    genre  duration                                        actors_list
# 3           9.0                 The Dark Knight          PG-13   Action       152  [u'Christian Bale', u'Heath Ledger', u'Aaron E...
# 5           8.9                    12 Angry Men      NOT RATED    Drama        96  [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...
# 6           8.9  The Good, the Bad and the Ugly      NOT RATED  Western       161  [u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...
# 9           8.9                      Fight Club              R    Drama       139  [u'Brad Pitt', u'Edward Norton', u'Helena Bonh...
# 11          8.8                       Inception          PG-13   Action       148  [u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'...

print(df_movies[~df_movies.genre.isin(['Action','Drama','Western'])].head())
# star_rating                                          title  ... duration                                        actors_list
# 0          9.3                       The Shawshank Redemption  ...      142  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...
# 1          9.2                                  The Godfather  ...      175    [u'Marlon Brando', u'Al Pacino', u'James Caan']
# 2          9.1                         The Godfather: Part II  ...      200  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...
# 4          8.9                                   Pulp Fiction  ...      154  [u'John Travolta', u'Uma Thurman', u'Samuel L....
# 7          8.9  The Lord of the Rings: The Return of the King  ...      201  [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...
